environments:
  basiq_enrich_non_prod_environments:
    environment_variables:
      ENVIRONMENT: non_prod
      PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/npm:/usr/local/bin/node
    pipelines:
      - basiq_enrich_nonprod_pipeline
    agents:
      - 473392eb-d48b-4d24-9386-9c165ffa4861
pipelines:
  basiq_enrich_nonprod_pipeline: # definition of basiq_enrich_pipeline
    group: basiq_enrich_nonprod
    label_template: "${mygit[:8]}"
    locking: off
    materials:
      mygit: # this is the name of material
        # keyword git says about type of material and url at once
        git: https://github.com/nikhilmahto/basiq-enrich-lambda-api.git
        branch: master
    stages: # list of stages in order
      - unit-testing-stage: # name of stage
          clean_workspace: true
          jobs:
            unit-testing-job: # name of the job
              tasks: # ordered list of tasks to execute in job unit-testing-job
               - script: | # indicates type of task
                  cd ./tcs-service/
                  pwd
                  npm install mocha nock chai --save-dev
                  npm install request request-promise
                  cd ..
                  pwd
